### ISSUE TITLE
Cubevalue function

### ISSUE THREAD

**Issue by milangr** [sql-bi/AnalyzeInExcel#10] opened 2020-10-26 08:03 UTC
CUBEVALUE Excel function does not work if I use Analyze in Excel extension.
But if I go thought Dax Studio, and then use the advanced tab > Excel, it works.

PBI version 2.86.727.0 64-bit
Excel version 16.0.13231.20372 64-bit

![image](https://user-images.githubusercontent.com/29591761/97147522-ef604200-1769-11eb-89fa-7fc3b04a7cba.png)

[PBISampleCubevalue.zip](https://github.com/sql-bi/AnalyzeInExcel/files/5437546/PBISampleCubevalue.zip)

**Comment by marcosqlbi** [comment] 2020-10-26 08:28
I am not sure about what is causing this. If you use "Convert to Formulas" in the PivotTable, it works correctly. When you write the CUBEVALUE manually it generates the error in your screenshot if you provide an empty string in the second argument. However, the same expression using DAX Studio returns "N/A" and not a valid number. While I agree that there is something strange, I'd like to know if you can provide an example where the result is a valid number using DAX Studio and an error using Analyze in Excel. Thanks!

**Comment by milangr** [comment] 2020-10-26 09:11
The error on this image occurs when I start to type the second argument.

**Comment by milangr** [comment] 2020-10-26 09:18
Here is a comprising.
Left part is from Analyze in Excel extension

![image](https://user-images.githubusercontent.com/29591761/97154678-7dd9c100-1774-11eb-8a8e-bd4e7a830449.png)

**Comment by milangr** [comment] 2020-10-26 09:21
Maybe the connection name poses a problem.

**Comment by marcosqlbi** [comment] 2020-10-31 22:26
Good news - the reason for the issue was not the file name, but a property that is automatically enabled when the ODC file is imported and was not set by creating the local connection. Fixed in version 1.1.3.
Please, try to download the updated version from https://www.sqlbi.com/tools/analyze-in-excel-for-power-bi-desktop/ and let me know if it works correctly. I'll wait a few days before enabling the automatic update to verify whether there are regressions.
Thanks!

**Closed as completed by marcosqlbi** 2020-10-31 22:26 UTC

**Comment by milangr** [comment] 2020-11-03 11:19
Its ok now.
Thank you Marco.

**Comment by marcosqlbi** [comment] 2020-11-03 11:23
Thanks for the feedback!
